# Generated by Django 4.1.5 on 2023-01-08 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Context",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_classpath", models.CharField(max_length=300)),
                ("query", models.TextField()),
                ("start_page", models.IntegerField()),
                ("num_data_pages", models.IntegerField()),
                ("page_length", models.IntegerField(default=100)),
                ("load_page_start_threshhold", models.IntegerField(default=6)),
                ("data", models.JSONField(blank=True)),
                ("data_time", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
