# Generated by Django 4.1.5 on 2023-01-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hypercells_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="context",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="context",
            name="load_page_start_threshhold",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="context",
            name="page_length",
            field=models.IntegerField(),
        ),
    ]
