# Generated by Django 4.1.5 on 2023-01-08 20:45

from django.db import migrations, models
import hypercells_api.models


class Migration(migrations.Migration):

    dependencies = [
        ("hypercells_api", "0002_alter_context_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="context",
            name="uid",
            field=models.CharField(
                default=hypercells_api.models.random_uid, max_length=100
            ),
        ),
    ]
