# Generated by Django 4.1.5 on 2023-01-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hypercells_api", "0004_alter_context_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="context",
            name="query_len",
            field=models.IntegerField(default=0),
        ),
    ]
