# Generated by Django 4.1.5 on 2023-01-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hypercells_api", "0005_context_query_len"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="context",
            name="model_classpath",
        ),
        migrations.AddField(
            model_name="context",
            name="model_class",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="context",
            name="model_module",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="context",
            name="query_len",
            field=models.IntegerField(),
        ),
    ]
