# Generated by Django 4.1.5 on 2023-01-09 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "hypercells_api",
            "0006_remove_context_model_classpath_context_model_class_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="context",
            old_name="load_page_start_threshhold",
            new_name="data_start_page",
        ),
        migrations.RenameField(
            model_name="context",
            old_name="num_data_pages",
            new_name="num_pages",
        ),
        migrations.RenameField(
            model_name="context",
            old_name="start_page",
            new_name="reload_page",
        ),
    ]
