# Generated by Django 4.1.5 on 2023-01-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "hypercells_api",
            "0007_rename_load_page_start_threshhold_context_data_start_page_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="context",
            name="uid",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
