# Generated by Django 4.1.5 on 2023-01-09 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hypercells_api", "0008_alter_context_uid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="context",
            name="query_len",
        ),
    ]
