# Generated by Django 4.1.5 on 2023-01-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hypercells_api", "0009_remove_context_query_len"),
    ]

    operations = [
        migrations.AddField(
            model_name="context",
            name="query_len",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
