# Generated by Django 4.1.5 on 2023-01-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hypercells_api", "0010_context_query_len"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="context",
            name="data",
        ),
        migrations.RemoveField(
            model_name="context",
            name="data_start_page",
        ),
        migrations.RemoveField(
            model_name="context",
            name="query_len",
        ),
        migrations.RemoveField(
            model_name="context",
            name="reload_page",
        ),
        migrations.AlterField(
            model_name="context",
            name="model_module",
            field=models.CharField(max_length=300),
        ),
    ]
