# Generated by Django 4.1.5 on 2023-01-19 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "hypercells_api",
            "0011_remove_context_data_remove_context_data_start_page_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="context",
            old_name="data_time",
            new_name="timestamp",
        ),
    ]
