# Generated by Django 4.1.5 on 2023-01-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hypercells_api", "0012_rename_data_time_context_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="context",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
