# Generated by Django 4.1.5 on 2023-02-02 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hypercells_api", "0013_alter_context_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="context",
            name="query",
        ),
    ]
