# Generated by Django 4.1.5 on 2023-02-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hypercells_api", "0014_remove_context_query"),
    ]

    operations = [
        migrations.AddField(
            model_name="context",
            name="query",
            field=models.BinaryField(default=b" "),
            preserve_default=False,
        ),
    ]
