# Generated by Django 4.1.5 on 2023-02-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hypercells_api", "0015_context_query"),
    ]

    operations = [
        migrations.AddField(
            model_name="context",
            name="loading_edge_pages",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
