# Generated by Django 4.1.5 on 2023-02-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hypercells_api", "0016_context_loading_edge_pages"),
    ]

    operations = [
        migrations.AddField(
            model_name="context",
            name="displayed_fields",
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="context",
            name="hidden_fields",
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
