# Generated by Django 4.1.5 on 2023-02-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hypercells_api", "0017_context_displayed_fields_context_hidden_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="context",
            name="context_class",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
