# Generated by Django 4.1.5 on 2023-02-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Context",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=100, unique=True)),
                ("context_class", models.CharField(max_length=50)),
                ("model_module", models.CharField(max_length=300)),
                ("model_class", models.CharField(max_length=100)),
                ("query", models.BinaryField()),
                ("num_pages", models.IntegerField()),
                ("page_length", models.IntegerField()),
                ("loading_edge_pages", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now=True)),
                ("displayed_fields", models.JSONField()),
                ("hidden_fields", models.JSONField()),
            ],
        ),
    ]
