"""
Copyright 2023 Djangoist.com 
Distributed publicly under the CC BY-NC-ND 4.0 license
https://creativecommons.org/licenses/by-nc-nd/4.0/
"""

# Generated by Django 4.1.5 on 2023-02-10 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Context",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=100, unique=True)),
                ("context_class", models.CharField(max_length=50)),
                ("model_module", models.CharField(max_length=300)),
                ("model_class", models.CharField(max_length=100)),
                ("query", models.BinaryField()),
                ("display_thead", models.BooleanField()),
                ("num_pages", models.IntegerField()),
                ("page_length", models.IntegerField()),
                ("loading_edge_pages", models.IntegerField()),
                ("displayed_fields", models.JSONField()),
                ("hidden_fields", models.JSONField()),
                ("transmitted_fields", models.JSONField()),
                ("field_order", models.JSONField()),
                ("css_classes", models.JSONField()),
                ("enforce_security", models.BooleanField()),
                ("timestamp", models.DateTimeField(auto_now=True)),
                ("templates", models.JSONField()),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
