# Generated by Django 4.1.7 on 2023-02-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hypercells", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="context",
            name="hmac",
            field=models.BinaryField(default=b""),
            preserve_default=False,
        ),
    ]
