# Generated by Django 4.1.5 on 2023-02-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hypercells", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="context",
            name="css_styles",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
