# Generated by Django 4.1.5 on 2023-02-07 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hypercells", "0002_context_css_styles"),
    ]

    operations = [
        migrations.RenameField(
            model_name="context",
            old_name="css_styles",
            new_name="css_classes",
        ),
    ]
