# Generated by Django 4.1.5 on 2023-02-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hypercells", "0003_rename_css_styles_context_css_classes"),
    ]

    operations = [
        migrations.AddField(
            model_name="context",
            name="display_thead",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
