# Generated by Django 4.1.5 on 2023-02-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hypercells", "0005_context_enforce_security_context_generated_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="context",
            name="templates",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
