# Generated by Django 4.1.5 on 2023-02-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hypercells", "0006_context_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="context",
            name="transmitted_fields",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
