# Generated by Django 4.1.5 on 2023-01-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="first_name",
            field=models.CharField(db_index=True, max_length=60),
        ),
    ]
