"""
Copyright 2023 Djangoist.com 
Distributed publicly under the CC BY-NC-ND 4.0 license
https://creativecommons.org/licenses/by-nc-nd/4.0/
"""

# Generated by Django 4.1.5 on 2023-02-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(db_index=True, max_length=60)),
                ("last_name", models.CharField(db_index=True, max_length=60)),
                ("company_name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=100)),
                ("county", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                ("zip", models.CharField(max_length=5)),
                ("phone1", models.CharField(max_length=12)),
                ("phone2", models.CharField(max_length=12)),
                ("email", models.CharField(max_length=200)),
                ("web", models.CharField(max_length=400)),
            ],
        ),
    ]
